# Generated by Django 4.0.1 on 2022-03-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
